### ISSUE TITLE
can't use function in SequenceField

### ISSUE THREAD

**Issue by ABorovenskyi** [nauyey/factory#9]
I'm trying to implement simple factory, using an example from Readme, but getting next error:
`cannot use func literal (type func(int64) interface {}) as type factory.SequenceFieldValue in argument to def.SequenceField`

here is my code
```go 
import (
  "github.com/nauyey/factory/def"
  "fmt"
)

type Customer struct {
  Name string
}

var CustomerFactory = def.NewFactory(Customer{}, "",
  def.SequenceField("Name", 1, func(n int64) interface{} {
    return fmt.Sprint("Name", n)
  }),
)
```

I use version: v0.2.0, revision: "a3bf873c5a1323620b4bfaf180453093f3928b69"

**Comment by nauyey** [comment]
@ABorovenskyi Good catch!
